import 'server-only';
import { isProduction } from '@/lib/config/env';
import { serverConfig } from '@/lib/config/env.server';

/**
 * OTP provider abstraction (prompt §13). Adapters are selected by
 * OTP_PROVIDER. The `mock` provider is permitted ONLY outside production; the
 * factory hard-fails if it is selected in production.
 *
 * NOTE: real providers below are integration stubs — they define the contract
 * and where credentials plug in. They must be completed with the contracted
 * Saudi messaging provider before launch (see docs/LAUNCH_CHECKLIST.md).
 */

export interface SendResult {
  ok: boolean;
  providerRef?: string;
  error?: string;
}

export interface OtpProvider {
  readonly name: string;
  /** Deliver a code to an E.164 number. The code is generated by the caller. */
  send(e164: string, code: string): Promise<SendResult>;
}

/** Dev-only provider. Never delivers a real SMS; never exposes the code in prod. */
class MockOtpProvider implements OtpProvider {
  readonly name = 'mock';
  async send(e164: string, code: string): Promise<SendResult> {
    // Visible only in server logs during development. Guarded by the factory
    // so this class can never be constructed in production.
    // eslint-disable-next-line no-console
    console.info(`[otp:mock] would send code to ${e164} (dev only): ${code}`);
    return { ok: true, providerRef: 'mock' };
  }
}

class TwilioVerifyProvider implements OtpProvider {
  readonly name = 'twilio';
  async send(e164: string, _code: string): Promise<SendResult> {
    // With Twilio Verify, Twilio generates/verifies the code; the abstraction
    // still accepts our code for providers that send our own. Wire real REST
    // call here using TWILIO_* credentials.
    if (!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN) {
      return { ok: false, error: 'twilio_not_configured' };
    }
    void e164;
    return { ok: false, error: 'twilio_adapter_not_implemented' };
  }
}

class UnifonicProvider implements OtpProvider {
  readonly name = 'unifonic';
  async send(e164: string, code: string): Promise<SendResult> {
    if (!process.env.UNIFONIC_APP_SID) {
      return { ok: false, error: 'unifonic_not_configured' };
    }
    void e164;
    void code;
    return { ok: false, error: 'unifonic_adapter_not_implemented' };
  }
}

let cached: OtpProvider | null = null;

export function getOtpProvider(): OtpProvider {
  if (cached) return cached;
  const selected = serverConfig.otpProvider;

  if (selected === 'mock') {
    if (isProduction) {
      // Hard fail — a test OTP provider must never run in production (prompt §13).
      throw new Error('FATAL: OTP_PROVIDER=mock is not allowed in production.');
    }
    cached = new MockOtpProvider();
  } else if (selected === 'twilio') {
    cached = new TwilioVerifyProvider();
  } else if (selected === 'unifonic') {
    cached = new UnifonicProvider();
  } else {
    throw new Error(`Unknown OTP_PROVIDER: ${selected}`);
  }
  return cached;
}
